---
title: "beRi-proposal"
author: "Rob Gilmore"
date: "October 25, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Preface

  The R community is composed of various types of people who use R in different ways.  However, one of the biggest themes amongst R users and the sciences in general is the idea of reproducible research.  "Containerization" via docker has become a useful means to make an R project reproducible.  The [containerit](https://github.com/o2r-project/containerit) and [rocker](https://github.com/rocker-org/rocker) projects are both great examples stemming from the usefulness of containerization.  However, R users don't alwasy have the means to utilize docker containers for R.  This can be particullarly true in academic settings where system administrators are under heavy workload and/or are hesitant to utilize a technology that could render the system [vulnerable](https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface).  In these types of situations  [conda](https://docs.anaconda.com/anaconda/user-guide/tasks/use-r-language/) is by far one of the most popular options for reproducibility.  Other workflows involve the use of R packages including [packrat](https://github.com/rstudio/packrat), [checkpoint](https://github.com/RevolutionAnalytics/checkpoint)(MRAN), [miniCRAN](https://github.com/andrie/miniCRAN), [drat](https://github.com/eddelbuettel/drat), [workflowr](https://github.com/jdblischak/workflowr), and [rbundler](https://cran.r-project.org/web/packages/rbundler/index.html).  While these packages have their use cases, they limit users to interactive R (the R shell).
  Another useful concept for programming languages in general is the idea of a programming library coupled with a package manager.  Python has [pip](https://pypi.org/project/pip/) and [PyPi](https://pypi.org/), Javascript has the [npm-client](https://github.com/npm/cli) and [npm-registry](https://docs.npmjs.com/misc/registry), and Ruby has the [gem-client](https://github.com/rubygems/rubygems) for [RubyGems.org](https://rubygems.org/).  R has [CRAN](https://cran.r-project.org/) and [Bioconductor](https://www.bioconductor.org/), which are programming libraries.  However, R doesn't have a traditional package manager for installing these packages from the command line.
  In certain use cases it might also be important for R users to install R from source.  Specifically, HPC systems generally need R installed from source because system admins want specific configurations.  HPC system users also might want to install R on their user profile in order to get a specific version of R or to have a custom configuration of R in their environment.  Other programming languages including Python ([pyenv](https://github.com/pyenv/pyenv)) and Ruby ([rbenv](https://github.com/rbenv/rbenv) and [ruby-build](https://github.com/jdblischak/workflowr)) have third party interfaces that manage the installation and management of various versions of the language.
  With these ideas in mind we would like to propose the [beRi](https://github.com/datasnakes/beRi): A Suite of Tools for Managing R.  beRi will depend on a series of independent tools that work towards providing new options for managing R virtual environments, R package management, R installation management, and other R utilities all from the command line.  beRi will be built on top of this toolset, and provide a more hollistic experience by adding project management and configuration.
  
  